// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { YDC_Post$Type } from "./YDC_Post";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["YDC_Post"]: YDC_Post$Type;
    ["contracts/YDC_Post.sol:YDC_Post"]: YDC_Post$Type;
  }

  interface ContractTypesMap {
    ["YDC_Post"]: GetContractReturnType<YDC_Post$Type["abi"]>;
    ["contracts/YDC_Post.sol:YDC_Post"]: GetContractReturnType<YDC_Post$Type["abi"]>;
  }
}
