/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface YDC_AnchoredSwapInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "EQ_1YDC_ETH_AMOUNT"
      | "ETH2YDC"
      | "YDC2ETH"
      | "acceptOwnership"
      | "acceptOwnershipForMe"
      | "owner"
      | "pendingOwner"
      | "renounceOwnership"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Event_ETH2YDC"
      | "Event_YDC2ETH"
      | "OwnershipTransferStarted"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "EQ_1YDC_ETH_AMOUNT",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "ETH2YDC", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "YDC2ETH",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acceptOwnershipForMe",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "EQ_1YDC_ETH_AMOUNT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ETH2YDC", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "YDC2ETH", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptOwnershipForMe",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace Event_ETH2YDCEvent {
  export type InputTuple = [
    sender: AddressLike,
    ethAmount: BigNumberish,
    ydcAmount: BigNumberish
  ];
  export type OutputTuple = [
    sender: string,
    ethAmount: bigint,
    ydcAmount: bigint
  ];
  export interface OutputObject {
    sender: string;
    ethAmount: bigint;
    ydcAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace Event_YDC2ETHEvent {
  export type InputTuple = [
    sender: AddressLike,
    ydcAmount: BigNumberish,
    ethAmount: BigNumberish
  ];
  export type OutputTuple = [
    sender: string,
    ydcAmount: bigint,
    ethAmount: bigint
  ];
  export interface OutputObject {
    sender: string;
    ydcAmount: bigint;
    ethAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferStartedEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface YDC_AnchoredSwap extends BaseContract {
  connect(runner?: ContractRunner | null): YDC_AnchoredSwap;
  waitForDeployment(): Promise<this>;

  interface: YDC_AnchoredSwapInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  EQ_1YDC_ETH_AMOUNT: TypedContractMethod<[], [bigint], "view">;

  ETH2YDC: TypedContractMethod<[], [void], "payable">;

  YDC2ETH: TypedContractMethod<[ydcAmount: BigNumberish], [void], "nonpayable">;

  acceptOwnership: TypedContractMethod<[], [void], "nonpayable">;

  acceptOwnershipForMe: TypedContractMethod<
    [target: AddressLike],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pendingOwner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "EQ_1YDC_ETH_AMOUNT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ETH2YDC"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "YDC2ETH"
  ): TypedContractMethod<[ydcAmount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "acceptOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "acceptOwnershipForMe"
  ): TypedContractMethod<[target: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "Event_ETH2YDC"
  ): TypedContractEvent<
    Event_ETH2YDCEvent.InputTuple,
    Event_ETH2YDCEvent.OutputTuple,
    Event_ETH2YDCEvent.OutputObject
  >;
  getEvent(
    key: "Event_YDC2ETH"
  ): TypedContractEvent<
    Event_YDC2ETHEvent.InputTuple,
    Event_YDC2ETHEvent.OutputTuple,
    Event_YDC2ETHEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferStarted"
  ): TypedContractEvent<
    OwnershipTransferStartedEvent.InputTuple,
    OwnershipTransferStartedEvent.OutputTuple,
    OwnershipTransferStartedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "Event_ETH2YDC(address,uint256,uint256)": TypedContractEvent<
      Event_ETH2YDCEvent.InputTuple,
      Event_ETH2YDCEvent.OutputTuple,
      Event_ETH2YDCEvent.OutputObject
    >;
    Event_ETH2YDC: TypedContractEvent<
      Event_ETH2YDCEvent.InputTuple,
      Event_ETH2YDCEvent.OutputTuple,
      Event_ETH2YDCEvent.OutputObject
    >;

    "Event_YDC2ETH(address,uint256,uint256)": TypedContractEvent<
      Event_YDC2ETHEvent.InputTuple,
      Event_YDC2ETHEvent.OutputTuple,
      Event_YDC2ETHEvent.OutputObject
    >;
    Event_YDC2ETH: TypedContractEvent<
      Event_YDC2ETHEvent.InputTuple,
      Event_YDC2ETHEvent.OutputTuple,
      Event_YDC2ETHEvent.OutputObject
    >;

    "OwnershipTransferStarted(address,address)": TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;
    OwnershipTransferStarted: TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
