// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Test_Chainlink$Type } from "./Test_Chainlink";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Test_Chainlink"]: Test_Chainlink$Type;
    ["contracts/Test_Chainlink.sol:Test_Chainlink"]: Test_Chainlink$Type;
  }

  interface ContractTypesMap {
    ["Test_Chainlink"]: GetContractReturnType<Test_Chainlink$Type["abi"]>;
    ["contracts/Test_Chainlink.sol:Test_Chainlink"]: GetContractReturnType<Test_Chainlink$Type["abi"]>;
  }
}
