// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { YDC_Certificate$Type } from "./YDC_Certificate";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["YDC_Certificate"]: YDC_Certificate$Type;
    ["contracts/YDC_Certificate.sol:YDC_Certificate"]: YDC_Certificate$Type;
  }

  interface ContractTypesMap {
    ["YDC_Certificate"]: GetContractReturnType<YDC_Certificate$Type["abi"]>;
    ["contracts/YDC_Certificate.sol:YDC_Certificate"]: GetContractReturnType<YDC_Certificate$Type["abi"]>;
  }
}
