// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { YDC_Market$Type } from "./YDC_Market";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["YDC_Market"]: YDC_Market$Type;
    ["contracts/YDC_Market.sol:YDC_Market"]: YDC_Market$Type;
  }

  interface ContractTypesMap {
    ["YDC_Market"]: GetContractReturnType<YDC_Market$Type["abi"]>;
    ["contracts/YDC_Market.sol:YDC_Market"]: GetContractReturnType<YDC_Market$Type["abi"]>;
  }
}
