// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { YDC_DAO$Type } from "./YDC_DAO";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["YDC_DAO"]: YDC_DAO$Type;
    ["contracts/YDC_DAO.sol:YDC_DAO"]: YDC_DAO$Type;
  }

  interface ContractTypesMap {
    ["YDC_DAO"]: GetContractReturnType<YDC_DAO$Type["abi"]>;
    ["contracts/YDC_DAO.sol:YDC_DAO"]: GetContractReturnType<YDC_DAO$Type["abi"]>;
  }
}
