// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { BaseERC721$Type } from "./BaseERC721";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["BaseERC721"]: BaseERC721$Type;
    ["contracts/base/BaseERC721.sol:BaseERC721"]: BaseERC721$Type;
  }

  interface ContractTypesMap {
    ["BaseERC721"]: GetContractReturnType<BaseERC721$Type["abi"]>;
    ["contracts/base/BaseERC721.sol:BaseERC721"]: GetContractReturnType<BaseERC721$Type["abi"]>;
  }
}
