// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { BaseUseRouter$Type } from "./BaseUseRouter";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["BaseUseRouter"]: BaseUseRouter$Type;
    ["contracts/base/BaseUseRouter.sol:BaseUseRouter"]: BaseUseRouter$Type;
  }

  interface ContractTypesMap {
    ["BaseUseRouter"]: GetContractReturnType<BaseUseRouter$Type["abi"]>;
    ["contracts/base/BaseUseRouter.sol:BaseUseRouter"]: GetContractReturnType<BaseUseRouter$Type["abi"]>;
  }
}
