// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface BaseUseRouter$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "BaseUseRouter",
  "sourceName": "contracts/base/BaseUseRouter.sol",
  "abi": [
    {
      "inputs": [],
      "stateMutability": "nonpayable",
      "type": "constructor"
    }
  ],
  "bytecode": "0x60806040527349155f5a274fc463e6ef9cefc122b51cd899303e6000806101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff160217905550348015606357600080fd5b50603f8060716000396000f3fe6080604052600080fdfea26469706673582212203a92f2ef780249edc8ed97752204f4c3fa7d9bf7c0cad434cd9e9e8f33c1621864736f6c634300081c0033",
  "deployedBytecode": "0x6080604052600080fdfea26469706673582212203a92f2ef780249edc8ed97752204f4c3fa7d9bf7c0cad434cd9e9e8f33c1621864736f6c634300081c0033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "BaseUseRouter",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<BaseUseRouter$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/base/BaseUseRouter.sol:BaseUseRouter",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<BaseUseRouter$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "BaseUseRouter",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<BaseUseRouter$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/base/BaseUseRouter.sol:BaseUseRouter",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<BaseUseRouter$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "BaseUseRouter",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<BaseUseRouter$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/base/BaseUseRouter.sol:BaseUseRouter",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<BaseUseRouter$Type["abi"]>>;
}
