// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { YDC_Course$Type } from "./YDC_Course";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["YDC_Course"]: YDC_Course$Type;
    ["contracts/YDC_Course.sol:YDC_Course"]: YDC_Course$Type;
  }

  interface ContractTypesMap {
    ["YDC_Course"]: GetContractReturnType<YDC_Course$Type["abi"]>;
    ["contracts/YDC_Course.sol:YDC_Course"]: GetContractReturnType<YDC_Course$Type["abi"]>;
  }
}
