/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  PointerInterface,
  PointerInterfaceInterface,
} from "../../../../../../@chainlink/contracts/src/v0.8/interfaces/PointerInterface";

const _abi = [
  {
    inputs: [],
    name: "getAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class PointerInterface__factory {
  static readonly abi = _abi;
  static createInterface(): PointerInterfaceInterface {
    return new Interface(_abi) as PointerInterfaceInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): PointerInterface {
    return new Contract(address, _abi, runner) as unknown as PointerInterface;
  }
}
