// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { YDC_Issuer$Type } from "./YDC_Issuer";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["YDC_Issuer"]: YDC_Issuer$Type;
    ["contracts/YDC_Issuer.sol:YDC_Issuer"]: YDC_Issuer$Type;
  }

  interface ContractTypesMap {
    ["YDC_Issuer"]: GetContractReturnType<YDC_Issuer$Type["abi"]>;
    ["contracts/YDC_Issuer.sol:YDC_Issuer"]: GetContractReturnType<YDC_Issuer$Type["abi"]>;
  }
}
